version: "3"
  services:
    nginx:
      container_build: nginx
      env_file:.env
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      image: nginx:latest
      ports:
        - "430:430"

    mariadb:
      
    wordpress:
      volumes:
        - DB: requirements/wordpress
