version: '3.8'

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
       - mariadb
    restart: on-failure
    expose:
       - "9000"
    volumes:
       - wordpress:/var/www/wordpress
volumes:
  wordpress:
    driver: local
    driver_opts:
    type: 'none'
    o: 'bind'
    device: '/home/debian-username/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/debian-username/data/mariadb'

networks:
  inception:
    driver: bridge
