version: "3"
  services:
    nginx:
      build: 
        context: requirements/nginx
        dockerfile: Dockerfile
        image: requirements/nginx
      ports:
        - "430:430"

    mariadb:
      image: requirements/mariadb
    wordpress:
      image: requirements/wordpress
      volumes:
        - DB: requirements/wordpress
